function createfigure(X1, YMatrix1, YMatrix2, X2, YMatrix3, YMatrix4, X3, YMatrix5, YMatrix6)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2,X2,YMATRIX3,YMATRIX4,X3,YMATRIX5,YMATRIX6)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  X2:  vector of x data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data
%  X3:  vector of x data
%  YMATRIX5:  matrix of y data
%  YMATRIX6:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2013 16:01:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.583837209302326 0.213405797101449 0.341162790697674]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.6]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.3 0.1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Parent',axes1,'Color',[0 0 1]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create ylabel
ylabel('Position (m)','FontSize',12);

% Create title
title('A','FontSize',18);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.213405797101449 0.341162790697674]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 0.6]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-0.3 1.4]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix2,'Parent',axes2,'Color',[0 0 1]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create ylabel
ylabel('Velocity (m/s)','FontSize',12);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.410797101449275 0.583837209302326 0.213405797101449 0.341162790697674]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[-0.3 0.1]);
box(axes3,'on');
hold(axes3,'all');

% Create multiple lines using matrix input to plot
plot(X2,YMatrix3,'Parent',axes3,'Color',[0 0 1]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create title
title('B','FontSize',18);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.410797101449275 0.11 0.213405797101449 0.341162790697674]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[-0.3 1.4]);
box(axes4,'on');
hold(axes4,'all');

% Create multiple lines using matrix input to plot
plot(X2,YMatrix4,'Parent',axes4,'Color',[0 0 1]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create subplot
subplot1 = subplot(2,3,3,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 0.8]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-0.3 0.1]);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix5,'Parent',subplot1,'Color',[0 0 1]);
set(plot1(1),'Color',[1 0 0]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create title
title('C','FontSize',18);

% Create subplot
subplot2 = subplot(2,3,6,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 0.8]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.3 1.4]);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix6,'Parent',subplot2,'Color',[0 0 1]);
set(plot2(1),'Color',[1 0 0]);

% Create xlabel
xlabel('Time (s)','FontSize',12);

% Create arrow
annotation(figure1,'arrow',[0.846030473135525 0.823749916466185],...
    [0.762942779291553 0.816996262112035]);

% Create textbox
annotation(figure1,'textbox',...
    [0.785234161988773 0.69983866746717 0.108911788291901 0.0542634572158896],...
    'String',{'The 2nd-5th trials'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.809067774381174 0.325792474227332 0.0840040096230955 0.0542634572158896],...
    'String',{'The 1st trial'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.703034576234497 0.855102887057482 0.0840040096230955 0.0542634572158896],...
    'String',{'The 1st trial'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

% Create arrow
annotation(figure1,'arrow',[0.759969325153374 0.782616756617818],...
    [0.871559633027523 0.854582287573999]);

% Create arrow
annotation(figure1,'arrow',[0.811658305450431 0.784575723264622],...
    [0.359506370355557 0.33054431945173]);

% Create arrow
annotation(figure1,'arrow',[0.759672224244311 0.77181802892895],...
    [0.21320067661592 0.272770582306578]);

% Create textbox
annotation(figure1,'textbox',...
    [0.710151518532501 0.159897178144783 0.108911788291901 0.0542634572158896],...
    'String',{'The 2nd-5th trials'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'LineStyle','none');

