function createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 03-Apr-2012 13:53:00

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,2,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-10 160]);
box(subplot1,'on');
hold(subplot1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',1.5);
set(plot1(1),'DisplayName','Robust ADP');
set(plot1(2),'LineStyle','-.','Color',[1 0 0],'DisplayName','Unlearned');

% Create xlabel
xlabel('time (sec)');

% Create ylabel
ylabel('Rotor angle (degree)');

% Create title
title('Generator 2');

% Create subplot
subplot2 = subplot(2,1,1,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-100 300]);
box(subplot2,'on');
hold(subplot2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',1.5);
set(plot2(1),'DisplayName','Robust ADP');
set(plot2(2),'LineStyle','-.','Color',[1 0 0],'DisplayName','Unlearned');

% Create xlabel
xlabel('time (sec)');

% Create ylabel
ylabel('Rotor Angle (degree)');

% Create title
title('Generator 1');

% Create legend
legend(subplot2,'show');

% Create legend
legend(subplot1,'show');

% Create textbox
annotation(figure1,'textbox',...
    [0.140013062409289 0.348463536897226 0.205095791001451 0.0559105431309892],...
    'String',{'Oscillation started'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.235484760522496 0.617600917088918 0.111394775036285 0.0559105431309892],...
    'String',{'Learning'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.245644412191581 0.151147242967513 0.108492017416546 0.0559105431309892],...
    'String',{'Learning'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create arrow
annotation(figure1,'arrow',[0.217387518142235 0.207547169811321],...
    [0.363984025559104 0.28594249201278]);

% Create arrow
annotation(figure1,'arrow',[0.188679245283019 0.21044992743106],...
    [0.863217252396166 0.731629392971246]);

% Create textbox
annotation(figure1,'textbox',...
    [0.373046444121916 0.843607306865276 0.240886792452831 0.0559105431309891],...
    'String',{'Controller updated'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.379171262699564 0.339645645523423 0.236213352685051 0.0559105431309892],...
    'String',{'Controller updated'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create arrow
annotation(figure1,'arrow',[0.428156748911466 0.380261248185777],...
    [0.851437699680511 0.742811501597444]);

% Create arrow
annotation(figure1,'arrow',[0.400580551523948 0.36742934051144],...
    [0.349840255591054 0.297939778129952]);

% Create textbox
annotation(figure1,'textbox',...
    [0.135978229317852 0.854086540092115 0.205095791001451 0.0559105431309892],...
    'String',{'Oscillation started'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

